### PR TITLE
Bittrex has not made any statements for or against

### PR DESCRIPTION
**Pull request by jyap808**
Taking a similar stance to KeepKey in #10

Bittrex has not made a statement for or against Segwit2X. It has always been the stance of Bittrex remain neutral in discussions like this.

Bittrex did not sign the NYA. This does not imply we are for or against Segwit2X.

### CODE REVIEW

**Comment by nvk** [comment]
If they ask to be removed, would be happy to remove it.

**Comment by jyap808** [comment]
I represent Bittrex. Please remove it.

Further public comment https://twitter.com/jyap/status/899068724564467712

**Comment by nvk** [comment]
There is nothing on your profile related to it. Maybe a missed something. Just tweet from the official account.

**Comment by jyap808** [comment]
Look, I wrote this:
https://support.bittrex.com/hc/en-us/articles/115000808991

As well as most of the articles here:
https://support.bittrex.com/hc/en-us/sections/203283828-Information

**Comment by rikur** [comment]
Looks like a somewhat legit PR, but I agree with @nvk that a more direct word from Bittrex would be preferable.

The KeepKey PR was made by a member of a the @keepkey Github organization.

**Comment by jyap808** [comment]
Refer to my profile page with GitHub link verification:

https://support.bittrex.com/hc/en-us/profiles/20564693608-Julian-Yap

**Comment by nvk** [comment]
There you go, once they reply will merge it https://twitter.com/nvk/status/900076243403632649

**Pull request merged**
