### PR TITLE
remove Bity

### PR DESCRIPTION
**Pull request by rachyandco**
Remove

### CODE REVIEW

**Comment by rachyandco** [comment]
yes otherwise i would not be requesting this.

**Comment by nvk** [comment]
The community reach out to most businesses. Mistakes can happen. If anyone from Bity wants it removed. It would be immediately removed.

**Comment by rachyandco** [comment]
this is ridiculous.

**Comment by rachyandco** [comment]
https://twitter.com/alexis_roussel/status/900701127771127809

**Comment by nvk** [comment]
Will do, Please fix the conflict

**Comment by rachyandco** [comment]
wtf

**Comment by rachyandco** [comment]
so to understand:

we say nothing, then you put us on a list of nay sayer, which is not true, and then it is up to us to prove and remove this mess?

just remove us

**Comment by nvk** [comment]
This is a list of companies that did not sign the NYA. Did you sign it? No. Happy to remove it. Please fix the merge conflic

**Comment by rachyandco** [comment]
@robzon  

Title "NOB2X - List of B2X non supporters" is misleading
Picture is misleading
We received comments from people being mislead by the presentation of this page. 

So the whole point of the list is a fail

**Comment by robzon** [comment]
@rachyandco I see. Yeah, sounds like the message should be much clearer then. Not associated with the page, but sorry your business had some issues because of it. Best of luck!

**Comment by ggravier** [comment]
It really looks like this list is about bullying people / businesses into accepting something (whatever it is, but in this case SegWit2x). This is not the way open source (and GitHub) is really supposed to be used. Consensus works so much better than pressure and bullying. You guys have it all wrong. Bity is right to make a fuss about this.

**Pull request merged**
